language: shell

matrix:
  include:
    - os: windows
      env: OS=Windows
      before_script: echo "Configlet checks not enabled for Windows builds"
  fast_finish: true

install:
  - bin/install-pester.sh

before_script:
  - bin/fetch-configlet
  - bin/configlet lint .

script:
  - bin/run-tests.sh
